production:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/limspecProduction
    log_level: WARNING


staging:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/limspecStaging
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    solr_home: solr
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING