class CreateProductData < ActiveRecord::Migration
  def up
    Product.create([
      { :name => "ACD/AutoChrom MDS", :vendor => "Advanced Chemistry Development, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "ACD/Chrom Workbook", :vendor => "Advanced Chemistry Development, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "ACD/ChromGenius", :vendor => "Advanced Chemistry Development, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "EZChrom", :vendor => "Agilent Technologies, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Galaxie", :vendor => "Agilent Technologies, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "OpenLAB CDS", :vendor => "Agilent Technologies, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Bio-2000", :vendor => "Beijing Teleh Electronic Tech Co., Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "China\r" },
      { :name => "HyStar", :vendor => "Bruker Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "GPMAW", :vendor => "ChemSW, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Mass Spec Tools", :vendor => "ChemSW, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Clarity", :vendor => "DataApex, spol. sro", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "Czech Republic\r" },
      { :name => "Chromeleon", :vendor => "Dionex Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Chromatography Data System", :vendor => "E-Chrom Tech Co., Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "Taiwan\r" },
      { :name => "PC/Chrom", :vendor => "H&A Scientific, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Chromnav", :vendor => "Jasco Europe Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "Italy\r" },
      { :name => "Chrom Perfect LSI", :vendor => "Justice Laboratory Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Chrom Perfect Spirit", :vendor => "Justice Laboratory Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Laura 4", :vendor => "LabLogic Systems Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "LimsLink CDS", :vendor => "Labtronics Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "Canada\r" },
      { :name => "OpenChrom", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "N/A\r" },
      { :name => "Chromera", :vendor => "PerkinElmer Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Mint Miner", :vendor => "Promium, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "WinGPC UniChrom", :vendor => "PSS Polymer Standards Service GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "Germany\r" },
      { :name => "Malcom", :vendor => "Schlumberger Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "LabSolutions", :vendor => "Shimadzu Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "Japan\r" },
      { :name => "Atlas CDS", :vendor => "Thermo Scientific", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "ChromQuest", :vendor => "Thermo Scientific", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "EnviroLab Forms", :vendor => "Thermo Scientific", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "QuanLab Forms", :vendor => "Thermo Scientific", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "Empower 3", :vendor => "Waters Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "United States\r" },
      { :name => "MultiChro", :vendor => "Yullin Technologies Co., Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "CDMS", :headquarterLocation => "South Korea\r" },
      { :name => "Limsophy DoDoc", :vendor => "AAC Infotray AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Switzerland\r" },
      { :name => "Accelrys ELN", :vendor => "Accelrys, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Contur ELN/iLabber", :vendor => "Accelrys, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "LogiLab ELN", :vendor => "Agaram Technologies Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "India\r" },
      { :name => "ELN BioLab", :vendor => "AgiLab SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "France\r" },
      { :name => "ChemLab", :vendor => "AgiLab SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "France\r" },
      { :name => "FormuLab", :vendor => "AgiLab SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "France\r" },
      { :name => "LabCollector", :vendor => "AgileBio", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "OpenLAB ELN", :vendor => "Agilent Technologies, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "CompliantPad", :vendor => "Amphora Research Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "OpenELN", :vendor => "Amphora Research Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "PatentPad", :vendor => "Amphora Research Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "PatentSafe", :vendor => "Amphora Research Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Ensemble ELN", :vendor => "ArtusLabs, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "ArxLab Electronic Notebook", :vendor => "Arxspan, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "shareSignELN", :vendor => "Asseco Danmark A/S", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Denmark\r" },
      { :name => "ActiveLN", :vendor => "ATGC Labs, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Electronic Lab Notebook", :vendor => "BiochemLab Solutions", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "E-Notebook", :vendor => "CambridgeSoft Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Espresso ELN", :vendor => "ChemBytes", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Switzerland\r" },
      { :name => "CBIS", :vendor => "ChemInnovation Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "iPad ELN", :vendor => "Cognium Systems SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "France\r" },
      { :name => "Laboratory Manager Plus", :vendor => "CompuDrug International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Contur ELN/iLabber", :vendor => "Contur Software AB", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Sweden\r" },
      { :name => "Core ELN", :vendor => "Core Informatics, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "ChemCart ELN", :vendor => "DeltaSoft, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Studies Notebook", :vendor => "Dotmatics Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United Kingdom\r" },
      { :name => "ePro", :vendor => "eNovalys SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "France\r" },
      { :name => "ensochemLab", :vendor => "enso Software GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Germany\r" },
      { :name => "Electronic Lab Notebook", :vendor => "Evolvus Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "India\r" },
      { :name => "EZQuant-ELN", :vendor => "EZQuant Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Israel\r" },
      { :name => "FORMULATOR", :vendor => "FORMULATOR Software, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "SLims", :vendor => "Genohm BVBA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Belgium\r" },
      { :name => "eJournal", :vendor => "HiTec Zang GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Germany\r" },
      { :name => "eStudy", :vendor => "iAdvantage Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "BioBook", :vendor => "ID Business Solutions Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United Kingdom\r" },
      { :name => "ChemBook", :vendor => "ID Business Solutions Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United Kingdom\r" },
      { :name => "E-WorkBook", :vendor => "ID Business Solutions Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United Kingdom\r" },
      { :name => "irisnote", :vendor => "irisnote, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "eNovator", :vendor => "KineMatik Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "benchsys-lab", :vendor => "Labage SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Belgium\r" },
      { :name => "LabArchives", :vendor => "LabArchives, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "LABTrack", :vendor => "LABTrack, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Nexxis ELN", :vendor => "Labtronics Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Canada\r" },
      { :name => "eNotebook", :vendor => "LABVANTAGE Solutions, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "LabWare ELN", :vendor => "LabWare, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Chemia", :vendor => "Laurus Infosystems Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "India\r" },
      { :name => "NoteBookMaker", :vendor => "NoteBookMaker, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Online Worksheet", :vendor => "Online LIMS Canada Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Canada\r" },
      { :name => "CyNote", :vendor => "Open source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "N/A\r" },
      { :name => "Indigo ELN", :vendor => "Open source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "N/A\r" },
      { :name => "LabTrove", :vendor => "Open source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "N/A\r" },
      { :name => "open enventory", :vendor => "Open source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "N/A\r" },
      { :name => "E-Notebook, Ensemble", :vendor => "PerkinElmer Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "quattro/LJ", :vendor => "quattro research GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Germany\r" },
      { :name => "eCAT", :vendor => "Research Innovations Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Scotland\r" },
      { :name => "Sciency", :vendor => "RURO Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Scilligence ELN", :vendor => "Scilligence Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "hivebench", :vendor => "shazino SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "France\r" },
      { :name => "SIMATIC IT R&D", :vendor => "Siemens AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Germany\r" },
      { :name => "SparkLix", :vendor => "SparkLix Bio IT Corp.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Datacloud", :vendor => "SPLhost, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "STARLIMS Electronic Notebook", :vendor => "STARLIMS Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Study Director", :vendor => "Studylog Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "Sysment Notebook", :vendor => "Sysment Kft.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "Hungary\r" },
      { :name => "SigmaCERF", :vendor => "Systat Software Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United Kingdom\r" },
      { :name => "Labsform", :vendor => "Terrington York Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United Kingdom\r" },
      { :name => "Gene Inspector", :vendor => "Textco BioSoftware, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "BioRails ELN", :vendor => "The Edge Software Consultancy Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United Kingdom\r" },
      { :name => "NuGenesis 8", :vendor => "Waters Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "ELN", :headquarterLocation => "United States\r" },
      { :name => "LogiLab SDMS", :vendor => "Agaram Technologies Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "SDMS", :headquarterLocation => "India\r" },
      { :name => "OpenLAB ECM", :vendor => "Agilent Technologies, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "SDMS", :headquarterLocation => "United States\r" },
      { :name => "Nexxis SDMS", :vendor => "Labtronics Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "SDMS", :headquarterLocation => "Canada\r" },
      { :name => "Labcore", :vendor => "Poplar Solutions, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "SDMS", :headquarterLocation => "United States\r" },
      { :name => "STARLIMS", :vendor => "STARLIMS Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "SDMS", :headquarterLocation => "United States\r" },
      { :name => "NuGenesis 8", :vendor => "Waters Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "SDMS", :headquarterLocation => "United States\r" },
      { :name => "OhNo!", :vendor => "2nd Sight Solutions", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "ARDAS", :vendor => "3rd Millennium, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Limsophy LIMS", :vendor => "AAC Infotray AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Switzerland\r" },
      { :name => "ABB LIMS", :vendor => "ABB Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Accelrys LIMS", :vendor => "Accelrys, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "BESTMIX LIMS", :vendor => "Adifo NV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Belgium\r" },
      { :name => "PHIMS", :vendor => "Advanced Business Software", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "uniLIME", :vendor => "Advanced Technical Software", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Austria\r" },
      { :name => "VADDS", :vendor => "Advanced Technology Corp.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "VETSTAR", :vendor => "Advanced Technology Corp.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "QuaLIS", :vendor => "Agaram Technologies Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "AgiLIMS", :vendor => "AgiLab SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "LabCollector", :vendor => "AgileBio", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LimsLink", :vendor => "Agilent Technologies, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LABbase", :vendor => "AJ Blomesystem GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "readyLIMS", :vendor => "AJ Blomesystem GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "CI-Master, LabTec", :vendor => "Alcor SPRL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Belgium\r" },
      { :name => "ECLIPSE", :vendor => "Alpha Technologies US, LP", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Enterprise ULTIMA", :vendor => "Alpha Technologies US, LP", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "SOLUTION Laboratoire", :vendor => "ALTIK SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "LabWay-LIMS", :vendor => "Ambidata Digital Innovation Solutions & Consulting, Lda.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Portugal\r" },
      { :name => "AIS LIMS", :vendor => "Analytical Information Systems, Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "scarabLIMS", :vendor => "arivis AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "ASM-LIMS", :vendor => "ASM Soft SL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Spain\r" },
      { :name => "LIMS2010, LIMS.net", :vendor => "Assaynet Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "Alis LIMS", :vendor => "Asystance V.O.F.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "ActiveLIMS", :vendor => "ATGC Labs, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "VisuaLab", :vendor => "Aurora Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Matrix Gemini", :vendor => "Autoscribe Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "datalabX", :vendor => "BARTELT GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Austria\r" },
      { :name => "MicroBLISS", :vendor => "Baytek International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "WebBLISS", :vendor => "Baytek International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "WinBLISS", :vendor => "Baytek International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "WebSQC", :vendor => "Baytek International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "BazeLab LIMS", :vendor => "Baze Technology AS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Norway\r" },
      { :name => "Bio-2000", :vendor => "Beijing Teleh Electronic Tech Co., Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "China\r" },
      { :name => "TL LAB2000", :vendor => "Beijing Teleh Electronic Tech Co., Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "China\r" },
      { :name => "LIMS ABC", :vendor => "BGASoft, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Bika LIMS", :vendor => "Bika Lab Systems (Pty) Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "South Africa\r" },
      { :name => "eLabJournal", :vendor => "Bio-ITech BV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "Labguru", :vendor => "BioData Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Geneious", :vendor => "Biomatters Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "New Zealand\r" },
      { :name => "MiniLIMS", :vendor => "BioTeam Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Quality Manager", :vendor => "bizzApps", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "BlazeLIMS", :vendor => "Blaze Systems Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "BodeLIMS", :vendor => "Bode Technology Group, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "SampleTrack", :vendor => "Bruker Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "BTLIMS", :vendor => "BTLIMS Technologies", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "O3 LIMS", :vendor => "Bytewize AB", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Sweden\r" },
      { :name => "O3 LIMSXpress", :vendor => "Bytewize AB", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Sweden\r" },
      { :name => "CaliberLIMS", :vendor => "Caliber Technologies Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "Caliber Pet-LIMS", :vendor => "Caliber Technologies Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "Workflow LIMS", :vendor => "CambridgeSoft Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "POLARIS", :vendor => "Camin Cargo Control, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Cargotester.com", :vendor => "Cargotrader, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "HORIZON Central", :vendor => "ChemWare, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "ChikPea LIMS", :vendor => "ChikPea, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Lab21 LIMS", :vendor => "Chromasoft GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "SDK", :vendor => "Cimarron Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "CSi LIMS", :vendor => "Civil Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "ClinAxys II", :vendor => "Clinical Systems Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "WinPath Enterprise", :vendor => "CliniSys", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "See vendors CliniSys and MIPS", :vendor => "CliniSys Group Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Q-SYS LIMS", :vendor => "Clyde Computing Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Codon LIMS", :vendor => "Codon Software Private Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "OmniLIMS", :vendor => "Columbia Energy & Environmental Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "ApolloLIMS", :vendor => "Common Cents Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Laboratory Manager Plus", :vendor => "CompuDrug International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LabSoft LIMS", :vendor => "Computing Solutions, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LabTrak", :vendor => "Condition Monitoring International, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "MADCAP", :vendor => "Contec Group International Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "New Zealand\r" },
      { :name => "Core LIMS", :vendor => "Core Informatics, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "eGECKO LIMS", :vendor => "CSS GmbH Dresden", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "Starfruit CrimeLab", :vendor => "Data Unlimited International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Starfruit DNA", :vendor => "Data Unlimited International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Starfruit GeneTell", :vendor => "Data Unlimited International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Starfruit IdentiTrack", :vendor => "Data Unlimited International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Starfruit Toxicology", :vendor => "Data Unlimited International, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "ALIS", :vendor => "Desert Oasis Software Company, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "diaLIMS", :vendor => "dialog EDV Systementwicklung GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "DipLABO", :vendor => "DIPOLE SARL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "limsExpress", :vendor => "Dynamic Databases, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "e-BiOData", :vendor => "e-BiOnary Technologies Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "eLab", :vendor => "eBioSys Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Australia\r" },
      { :name => "ElmTree System", :vendor => "ElmTree Systems, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "PhaLIMS", :vendor => "entimo AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "X-LIMS", :vendor => "EthoSoft, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "EuSoft.Lab", :vendor => "Eusoft Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Italy\r" },
      { :name => "FinaLims", :vendor => "Finalist Software Noord Nederland C.V.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "Forensic Advantage", :vendor => "Forensic Advantage Systems", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "DNA LIMS", :vendor => "Future Technologies, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LabScout LIMS", :vendor => "Genee Group, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LAB-2000", :vendor => "Genesis MicroSystems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "SLims", :vendor => "Genohm BVBA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Belgium, Switzerland\r" },
      { :name => "Clarity LIMS", :vendor => "GenoLogics Life Sciences Software Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "GoLIMS", :vendor => "GoInformatics, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "BioInfoStream", :vendor => "GyroDimensions, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "IntelliLIMS, SLIM", :vendor => "H&A Scientific, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Hach WIMS", :vendor => "Hach Company", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States, Germany\r" },
      { :name => "PetroLab", :vendor => "Hamsoo IT Consultants Co.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Iran\r" },
      { :name => "HiLIMS", :vendor => "HiTec Zang GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "HM-LIMS", :vendor => "HM-Software", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "Honeywell LIMS", :vendor => "Honeywell Process Solutions", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Uniformance Process Studio", :vendor => "Honeywell Process Solutions", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "CIMS", :vendor => "Hollison Technologies", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "CAQ=QSYS LIMS", :vendor => "IBS AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "LABS/Q", :vendor => "ICD. GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "LABS/QM", :vendor => "ICD. GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "LABS/R", :vendor => "ICD. GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "Core Facility Management", :vendor => "iLab Solutions, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Lab Management", :vendor => "iLab Solutions, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Illumina LIMS", :vendor => "Illumina, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "In Siliflo LIMS", :vendor => "In Siliflo, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "PIMS", :vendor => "Inflection Point Solutions, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Lab@link", :vendor => "Infomed C.S.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Greece\r" },
      { :name => "BSI", :vendor => "Information Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "SEER*DMS", :vendor => "Information Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "SQUISH", :vendor => "Information Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Provantis", :vendor => "Instem LSS Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Centrus", :vendor => "Instem LSS Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "NevisLIMS", :vendor => "Instrumentos Cient", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Spain\r" },
      { :name => "OmicsHub", :vendor => "Integromics SL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Spain\r" },
      { :name => "OmicsOffice", :vendor => "Integromics SL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Spain\r" },
      { :name => "Nova-LIMS", :vendor => "Interface Engineering Co. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "South Korea\r" },
      { :name => "INQAS", :vendor => "Interpec Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "INTRACES", :vendor => "Interpec Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "TrakCare Lab", :vendor => "InterSystems Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "FermWorks", :vendor => "Jova Solutions Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LIMS-plus", :vendor => "JusticeTrax, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "jwLIMS", :vendor => "jwConsulting GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "DairyLIMS", :vendor => "Kenny Agrisoft Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Ireland\r" },
      { :name => "Omega 11 LIMS", :vendor => "Khemia Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Kriti LIMS", :vendor => "Kriti Microsystems Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "benchsys", :vendor => "Labage SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Belgium\r" },
      { :name => "LabCloud", :vendor => "LabCloud, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LabKey Server", :vendor => "LabKey Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LabLite SQL LIMS", :vendor => "LabLite, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Debra 5", :vendor => "LabLogic Systems Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "PETra", :vendor => "LabLogic Systems Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Sara 5", :vendor => "LabLogic Systems Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "ELab, webLIMS", :vendor => "LabLynx, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LabPro, eQual", :vendor => "LabPro 2000 Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "New Zealand\r" },
      { :name => "myLIMS", :vendor => "Labsoft Tecnologia Ltda.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Brazil\r" },
      { :name => "Kuiper-LIMS", :vendor => "LabTech, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LABVANTAGE", :vendor => "LABVANTAGE Solutions, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LabWare LIMS", :vendor => "LabWare, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Lab Pro 2004", :vendor => "Latent Logics Infosoft Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "iLIMS", :vendor => "Laucks Technical Services, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Q-Cent", :vendor => "LeanRP", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "Labvironment", :vendor => "Lemm Tech Enterprises, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Labmatica LIMS", :vendor => "LIMS at work GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "lims+WARE/ASP", :vendor => "lims+WARE", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "lims+WARE/Results", :vendor => "lims+WARE", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "lims+WARE/Networks", :vendor => "lims+WARE", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "lims+WARE/UNIX", :vendor => "lims+WARE", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LINKS V3.3 LIMS", :vendor => "LINKSolutions SAA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Peru\r" },
      { :name => "Lims.net", :vendor => "Loc@soft", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "Lims1", :vendor => "LTech Australia Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Australia\r" },
      { :name => "LLMS", :vendor => "Lyons Information Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "MAQSIMA LAB+", :vendor => "MAQSIMA GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "LIAS", :vendor => "Megaware, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Track-IT", :vendor => "Micronic Europe BV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "GLIMS", :vendor => "MIPS NV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Belgium\r" },
      { :name => "MBioLIMS", :vendor => "Modul-Bio SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "Mongoose LIMS", :vendor => "Mongoose Coding", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "MSC-LIMS", :vendor => "Mountain States Consulting, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Moxie", :vendor => "Moxie Informatics, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Myfab LIMS", :vendor => "Myfab", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Sweden\r" },
      { :name => "caLIMS", :vendor => "National Cancer Institute", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "NOVA-LIMS", :vendor => "Novatek International", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "EnviroLIMS EWM,   LIMZ-RD, OasisLIMS, True-LIMZ CTL", :vendor => "Oasis Infotech Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "EnviroLIMS EWM,   LIMZ-RD, OasisLIMS, True-LIMZ CTL", :vendor => "Oasis Infotech Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "EnviroLIMS EWM,   LIMZ-RD, OasisLIMS, True-LIMZ CTL", :vendor => "Oasis Infotech Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "EnviroLIMS EWM,   LIMZ-RD, OasisLIMS, True-LIMZ CTL", :vendor => "Oasis Infotech Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "Biotracker LIMS", :vendor => "Ocimum Biosolutions Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "myLIMS", :vendor => "Odysis SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Switzerland\r" },
      { :name => "OnRepo", :vendor => "Online LIMS Canada Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "QLIMS", :vendor => "OnQ Software Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Australia\r" },
      { :name => "Bika LIMS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "caLIMS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "caTissue Plus", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "GNomEx", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "LAMA", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "Open-LIMS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "openBIS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "OpenELIS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "Screensaver HTS LIMS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "N/A\r" },
      { :name => "ProLab.Q Chemical & Manufacturing", :vendor => "Open.Co Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Italy\r" },
      { :name => "ProLab.Q Food & Beverage", :vendor => "Open.Co Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Italy\r" },
      { :name => "ProLab.Q LIMS", :vendor => "Open.Co Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Italy\r" },
      { :name => "ProLab.Q Wine", :vendor => "Open.Co Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Italy\r" },
      { :name => "Oracle Health Sciences Clinical Development Analytics", :vendor => "Oracle Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Oracle Health Sciences LabPas", :vendor => "Oracle Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "eL@b", :vendor => "Orsyx", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Israel\r" },
      { :name => "SPARCS", :vendor => "PANalytical BV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "eQMS::LIMS", :vendor => "Pardus d.o.o.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Croatia\r" },
      { :name => "PathData, ReproData, ToxData", :vendor => "Pathology Data Systems Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Switzerland\r" },
      { :name => "pdv-lims 3", :vendor => "pdv-software GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "LABWORKS", :vendor => "PerkinElmer Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "ChemLMS", :vendor => "Persistent Systems Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Phylum.Laboratoire", :vendor => "Phylum SARL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "Analisi", :vendor => "Polisystem Informatica Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Italy\r" },
      { :name => "Crime Fighter BEAST", :vendor => "Porter Lee Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Mikon LIMS", :vendor => "Prevas AB", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Sweden\r" },
      { :name => "BioProcessDB", :vendor => "ProBioData GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "LDMS", :vendor => "Process Solutions Canada Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "BookitLab", :vendor => "Prog4biz Software Solutions Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "Progeny LIMS", :vendor => "Progeny Software, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Caseman", :vendor => "Promadis Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Australia\r" },
      { :name => "Element LIMS", :vendor => "Promium, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Lab-i", :vendor => "QBCon (Pty) Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "South Africa\r" },
      { :name => "QUALIMS", :vendor => "QUALIMS SARL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "VersaLIMS.NET, WinLIMS.NET", :vendor => "Quality Systems International Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "THEMIS", :vendor => "RJ Lee Solutions, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "CQT2000 LIMS", :vendor => "RDS Nordest Srl", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Italy\r" },
      { :name => "UVIS", :vendor => "Ross Group Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "ezColony, FreezerPro, LIMS 24/7", :vendor => "RURO Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "SampleNavigator", :vendor => "SampleNavigator BV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "Exemplar Biomarker Discovery, Exemplar Dx LIMS, Exemplar Research LIMS", :vendor => "Sapio Sciences, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "PLIMS", :vendor => "Sarla Technologies Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "SciLIMS", :vendor => "Sciformatix Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "LIMSsolution", :vendor => "Shimadzu Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Japan\r" },
      { :name => "custom LIMS", :vendor => "Sibio SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "SIMATIC IT Unilab", :vendor => "Siemens AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "LabHQ", :vendor => "SkySource Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Spectrum", :vendor => "Sofcom (Private) Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Pakistan\r" },
      { :name => "SoftTrace LIMS", :vendor => "SoftTrace Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Ireland\r" },
      { :name => "LabScores", :vendor => "Software for Life Sciences BV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Netherlands\r" },
      { :name => "LabVantage BioBanking, LabVantage LIMS, LABVANTAGE Medical Suite, TasteBOSS, WilabLIMS/LimsBOSS", :vendor => "Software Point Oy", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Finland\r" },
      { :name => "RHAPSODY LIMS", :vendor => "Softwaresysteme Keeve GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "QESTField, QESTLab", :vendor => "Spectra QEST Australia Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Australia\r" },
      { :name => "STaCS", :vendor => "STaCS DNA Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "STARLIMS", :vendor => "STARLIMS Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "EE-LIMS, MicroLIMS", :vendor => "Stone Bond Technologies, LP", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Metabase", :vendor => "Summit Research Services", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "CALYPSO LIMS", :vendor => "Sylab M", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "Lab Keeper", :vendor => "System Approach, Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Russia\r" },
      { :name => "Logbook Discovery, TechWare MainTrac", :vendor => "TechWare Incorporated", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "BioRails LIMS", :vendor => "The Edge Software Consultancy Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Darwin, Galileo, Nautilus, SampleManager, Watson", :vendor => "Thermo Scientific", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Timeless LIMS", :vendor => "Timeless Medical Systems", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Canada\r" },
      { :name => "Seamless LIMS", :vendor => "Tieto Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Finland\r" },
      { :name => "LIMS Lyte, Tribal-LIMS", :vendor => "Tribal Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "lisa.lims", :vendor => "Triestram & Partner GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Germany\r" },
      { :name => "HAND, STAR, TAPS, TIME", :vendor => "Trilogy Group Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Qualoupe LIMS", :vendor => "Two Fold Software Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United Kingdom\r" },
      { :name => "FORMS II Lite", :vendor => "U.S. EPA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "UNIFlow", :vendor => "UNIConnect LC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Valdata LIMS", :vendor => "Valdata Systems USA, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "CCLAS", :vendor => "Ventyx, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "VATIM", :vendor => "Visual Access Health Systems Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "India\r" },
      { :name => "Wavefront LIMS", :vendor => "Wavefront Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "ARES, EDIlab, LimsOnLine", :vendor => "WESTcom Logiciels et Services SARL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "France\r" },
      { :name => "NAPIS", :vendor => "White Point Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "United States\r" },
      { :name => "Your Lab Data", :vendor => "YourLabData.com", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "Unknown\r" },
      { :name => "LabMate Enterprise", :vendor => "Yullin Technologies Co., Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIMS", :headquarterLocation => "South Korea\r" },
      { :name => "CLINILAN", :vendor => "A&T Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Japan\r" },
      { :name => "PHIMS", :vendor => "Advanced Business Software", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Bioserveur, Hexalis, ORBIS", :vendor => "Agfa HealthCare NV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Belgium\r" },
      { :name => "Alfa LIS", :vendor => "Alfa Wassermann, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Sunrise Patient Portal", :vendor => "Allscripts Healthcare Solutions, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Unilab-700", :vendor => "Alphasoft GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Germany\r" },
      { :name => "PROLIS", :vendor => "American Soft Solutions Corp.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Apex LIS", :vendor => "Apex HealthWare, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "ASPYRA LIS", :vendor => "Aspyra, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "datalabX", :vendor => "BARTELT GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Austria\r" },
      { :name => "Labmatrix", :vendor => "BioFortis, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Maxim LIS", :vendor => "Birlamedisoft Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "India\r" },
      { :name => "LabTrain", :vendor => "Bod", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Netherlands\r" },
      { :name => "BtB Software", :vendor => "BtB Software, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Labmate", :vendor => "Busysoft Systems Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "India\r" },
      { :name => "CorLabs", :vendor => "Cegeka NV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Belgium\r" },
      { :name => "Millennium PathNet, PowerChart", :vendor => "Cerner Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Clin1 Suite", :vendor => "Clin1, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "ClinAxys II", :vendor => "Clinical Systems Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United Kingdom\r" },
      { :name => "ClinLab LIS", :vendor => "ClinLab, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Polytech Laboratory Information System", :vendor => "Comp Pro Med, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "CGM Analytix, LabDAQ", :vendor => "CompuGroup Medical AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Germany\r" },
      { :name => "Rx-Care LIS", :vendor => "CompuMedical Health Care Solutions SAE Co.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Egypt\r" },
      { :name => "CSS LIS", :vendor => "Computer Service and Support, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Labgen LIS", :vendor => "Comtron Corp.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Cortex Live, CorteXchange", :vendor => "Cortex Medical Management Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "NetAcquire LIS", :vendor => "Custom Software Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Ireland\r" },
      { :name => "SilverLab", :vendor => "Desarrollo Aplicaciones Sanitarias SL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Spain\r" },
      { :name => "LabGEM", :vendor => "Diamond Computing Company", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "X/Lab", :vendor => "Dorner GmbH & Co. KG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Germany\r" },
      { :name => "Empower HIS", :vendor => "Emergency Care Dictation Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "GenesysNSL", :vendor => "Entre Technology Group", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "MediEaz LIS", :vendor => "Exleaz Solutions Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United Kingdom\r" },
      { :name => "FONET LIS", :vendor => "Fonet Bilgi Teknolojileri A.?.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Turkey\r" },
      { :name => "HMS Laboratory", :vendor => "Healthcare Management Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "e-Delphyn LIS", :vendor => "Hemasoft Software SL", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Spain\r" },
      { :name => "LAB/HEX LIS", :vendor => "Hex 'ff' Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "sLis", :vendor => "Infomed C.S.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Greece\r" },
      { :name => "BSI", :vendor => "Information Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "SEER*DMS", :vendor => "Information Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "SEER*STAT", :vendor => "Information Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "SQUISH", :vendor => "Information Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "EDGElab, SAPANET", :vendor => "INLOG SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "France, Germany\r" },
      { :name => "Centrus, Provantis", :vendor => "Instem LSS Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United Kingdom\r" },
      { :name => "LABLION", :vendor => "Integrated Business Solutions Group, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "OMNI-Lab", :vendor => "Integrated Software Solutions Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Australia\r" },
      { :name => "TrakCare", :vendor => "InterSystems Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Messenger", :vendor => "ISYS/Biovation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "AviCenna LIS", :vendor => "ITs 4 H.E.ALT.H s.a.l", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Lebanon\r" },
      { :name => "LabTrak", :vendor => "J&S Medical Associates, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "YASASII", :vendor => "Kameda Infologics Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Japan\r" },
      { :name => "Beethoven II", :vendor => "LabSoft, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "EZLink", :vendor => "LabSoft, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "LabNet", :vendor => "LabSoft, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "LTP Achiever", :vendor => "Labthroughput", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "LigoLab LIS", :vendor => "LigoLab, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "MediPATH", :vendor => "LRS Health Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Australia\r" },
      { :name => "MediPATH AP", :vendor => "LRS Health Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Australia\r" },
      { :name => "Horizon Lab", :vendor => "McKesson Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "DxCare", :vendor => "Medasys SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "France\r" },
      { :name => "DXLAB", :vendor => "Medasys SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "France\r" },
      { :name => "DxLabOne", :vendor => "Medasys SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "France\r" },
      { :name => "Merge LIS", :vendor => "Merge Healthcare Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "GLIMS", :vendor => "MIPS NV", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Belgium\r" },
      { :name => "Lab Online", :vendor => "Moonchase", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Belgium\r" },
      { :name => "Horizon", :vendor => "Mukon CC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "South Africa\r" },
      { :name => "PathWay", :vendor => "Mukon CC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "South Africa\r" },
      { :name => "MultiTech", :vendor => "Multidata Computer Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "AutoLims", :vendor => "NeTLIMS NJ, LLC", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Neusoft LIS", :vendor => "Neusoft Medical Systems Co., Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "China\r" },
      { :name => "DNLab", :vendor => "NoemaLife SpA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Italy\r" },
      { :name => "eLab.Sys", :vendor => "Northern Software, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "NovoPath", :vendor => "NovoPath, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Optimum Clinicals", :vendor => "NTT DATA Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Japan, United States\r" },
      { :name => "Oger Medical Information System", :vendor => "OGER SYSTEMS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Saudi Arabia\r" },
      { :name => "C4G BLIS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "N/A\r" },
      { :name => "caTissue Plus", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "N/A\r" },
      { :name => "OpenELIS", :vendor => "Open-source software solution", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "N/A\r" },
      { :name => "Oracle Health Sciences Clinical Development Center", :vendor => "Oracle Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Oracle Health Sciences LabPas", :vendor => "Oracle Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Orchard Harvest", :vendor => "Orchard Software Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Lab Plus", :vendor => "PCS Technology Limited", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "India\r" },
      { :name => "PDV-LIS II", :vendor => "pdv-software GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Germany\r" },
      { :name => "PathX", :vendor => "Physicians Independent Management Services, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "v-LAB", :vendor => "Point of Care Solutions Pty. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Australia\r" },
      { :name => "Winsoft LIS", :vendor => "Prestij Yaz?l?m ve Bilgi Sistemleri", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Turkey\r" },
      { :name => "WindoPath", :vendor => "Psyche Systems Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "LabHealth", :vendor => "Quality Software Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Rabbit EHR", :vendor => "Rabbit Healthcare Systems", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "SchuyLab", :vendor => "Schuyler House", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "SurroundLab", :vendor => "Seacoast Laboratory Data Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Servolab", :vendor => "Siemens AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Germany\r" },
      { :name => "TD-Synergy", :vendor => "Siemens AG", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Germany\r" },
      { :name => "SoftLab", :vendor => "Soft Computer Consultants, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "AutoLab", :vendor => "SofTov Medical Systems Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Israel\r" },
      { :name => "FONS Openlims", :vendor => "STAPRO s.r.o.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Czech Republic\r" },
      { :name => "ICE", :vendor => "Sunquest Information Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Sunquest Laboratory", :vendor => "Sunquest Information Systems, Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United States\r" },
      { :name => "Suvarna-HIS", :vendor => "Suvarna Technosoft (P) Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "India\r" },
      { :name => "Delphic LIS", :vendor => "Sysmex Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Japan\r" },
      { :name => "Modulab", :vendor => "Systelab Technologies SA", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Spain\r" },
      { :name => "SWISSLAB", :vendor => "Swisslab GmbH", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Germany\r" },
      { :name => "Synbiotix Hospital Information System", :vendor => "Synbiotix Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "United Kingdom\r" },
      { :name => "Silabmed", :vendor => "Tainosystems Inc.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Canada\r" },
      { :name => "TD-Synergy", :vendor => "Technidata SAS", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "France\r" },
      { :name => "FlexLab/Kemi", :vendor => "Tieto Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Finland\r" },
      { :name => "FlexLab/SymPathy", :vendor => "Tieto Corporation", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Finland\r" },
      { :name => "Timeless LIMS", :vendor => "Timeless Medical Systems", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Canada\r" },
      { :name => "molis", :vendor => "vision4health Laufenberg & Co.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "Switzerland\r" },
      { :name => "VATIM SOLUTIONS", :vendor => "Visual Access Health Systems Pvt. Ltd.", :description => "", :created_at => nil, :updated_at => nil, :productClass => "LIS", :headquarterLocation => "India\r" }
    ], :without_protection => true )



    ProductClass.create([
      { :className => "ELN", :created_at => "2014-02-27 04:33:18", :updated_at => "2014-02-27 04:33:18" },
      { :className => "LIMS", :created_at => "2014-02-27 04:33:18", :updated_at => "2014-02-27 04:33:18" },
      { :className => "LIS", :created_at => "2014-02-27 04:33:18", :updated_at => "2014-02-27 04:33:18" },
      { :className => "CDMS", :created_at => "2014-02-27 04:33:18", :updated_at => "2014-02-27 04:33:18" }
    ], :without_protection => true )

  end

  def down
  end
end
